/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
static yyconst short int yy_accept[261] =
    {   0,
        0,    0,   95,   94,   93,   78,   94,   90,   80,   73,
       94,   68,   69,   74,   75,   89,   76,   72,   79,   39,
       39,   86,   87,   81,   88,   82,   85,   38,   38,   66,
       67,   83,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   70,   84,
       71,   77,   55,    0,   43,    0,   60,   56,   63,    0,
        0,   58,   48,   61,   49,   62,   47,    0,   40,    0,
       91,   59,   40,    0,    0,   39,   39,   50,   52,   54,
       53,   51,   38,    0,   38,   64,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   27,   38,   38,   38,   38,

       38,   38,    4,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   65,   57,   42,   44,    0,    0,
        0,    0,   91,   40,   45,   46,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       26,   38,   38,   18,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
        0,   40,    0,    0,   92,   38,   38,   38,    1,   38,
        8,   20,   38,   38,   38,   38,    5,    3,   38,   38,
        6,   38,   17,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   21,   38,   38,   23,   38,

       38,   10,   29,   38,   38,   38,   38,   14,   38,   38,
       38,   38,   19,   38,   38,   38,   38,   38,   38,   37,
       38,   38,   28,   38,   38,   38,   38,   13,   32,   34,
       38,   38,   12,   16,   22,   30,   35,    7,   38,   38,
       38,   38,   38,   38,   11,   38,   38,   36,   38,   38,
       24,   38,    9,   31,    2,   15,   33,   38,   25,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   21,   22,   23,
       24,   25,   26,    1,   27,   28,   29,   27,   30,   27,
       27,   27,   31,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       32,   33,   34,   35,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   27,   46,   47,   48,   49,
       50,   51,   27,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1,    1,    1
    } ;

static yyconst short int yy_base[267] =
    {   0,
        0,    0,  387,  501,  501,  362,   59,  501,  361,   57,
       65,  501,  501,  358,   53,  501,   54,   55,   69,   69,
       75,  501,  501,   60,  356,   98,  501,    0,  110,  501,
      501,  354,  103,  322,  323,   83,   59,  121,   26,  324,
       76,  323,  331,   94,  312,  321,  318,  323,  501,   44,
      501,  501,  501,  174,  225,  276,  501,  501,  501,  327,
      378,  501,  501,  501,  501,  501,  501,  349,  123,  141,
        0,  501,  130,  142,  162,  168,  172,  339,  501,  501,
      501,  338,    0,  127,  136,  501,  311,  310,  311,  304,
      316,  303,  318,  305,  310,  296,  297,  294,  294,  297,

      294,  291,    0,  111,  295,  120,  293,  109,  138,  297,
      290,   45,  148,  295,  501,  501,  429,  501,  185,  193,
      204,  211,    0,  147,  501,  501,  289,  290,  299,  285,
      297,  290,  277,  165,  290,  288,  283,  275,  281,  284,
        0,  270,  274,    0,  274,  271,  261,  257,  259,  261,
      268,  254,  252,  252,  264,  254,  258,  261,  263,  252,
      201,  213,  233,  235,  501,  251,  246,  253,    0,  249,
        0,    0,  240,  248,  237,  244,    0,    0,  238,  235,
        0,  239,    0,  234,  233,  232,  229,  239,  228,  231,
      236,  234,  232,  222,  227,    0,  215,  227,    0,  219,

      220,    0,    0,  215,  214,  219,  210,    0,  217,  203,
      211,  206,    0,  214,  211,  213,  196,  205,  206,    0,
      196,  199,    0,  202,  193,  186,  186,    0,    0,    0,
      193,  188,    0,    0,    0,    0,    0,    0,  183,  181,
      163,  145,  157,  145,    0,  125,  103,    0,   96,   87,
        0,   60,    0,    0,    0,    0,    0,   45,    0,  501,
      485,  488,   77,  491,  494,  497
    } ;

static yyconst short int yy_def[267] =
    {   0,
      260,    1,  260,  260,  260,  260,  261,  260,  260,  260,
      262,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  263,  263,  260,
      260,  260,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  260,  260,
      260,  260,  260,  261,  261,  261,  260,  260,  260,  262,
      262,  260,  260,  260,  260,  260,  260,  260,  260,  264,
      265,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  263,  260,  263,  260,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,

      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  260,  260,  262,  260,  260,  264,
      264,  266,  265,  260,  260,  260,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      260,  260,  264,  264,  260,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,

      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,    0,
      260,  260,  260,  260,  260,  260
    } ;

static yyconst short int yy_nxt[566] =
    {   0,
        4,    5,    5,    4,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   28,   29,
       28,   30,    4,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   28,   41,   28,   42,   28,   28,   28,
       28,   43,   44,   45,   46,   47,   48,   28,   28,   28,
       49,   50,   51,   52,   55,   58,   63,  115,   56,   65,
       61,   68,  100,   69,   69,  101,   64,   66,   67,   83,
       59,   70,   78,   79,   56,   73,   71,   74,   74,  156,
       61,   73,   72,   76,   77,   56,   56,  157,   75,   95,

       56,   61,   61,  259,   75,  116,   61,   56,   96,   75,
       56,  258,   56,   61,   56,   75,   61,  103,   61,   92,
       61,   81,   82,   84,  104,   84,   93,  257,   85,   85,
       87,   88,   94,   89,   84,  256,   84,  107,  108,   85,
       85,   69,   69,  121,  121,  124,  124,  109,   69,   69,
      110,  150,  119,  122,   85,   85,  255,  143,   73,  119,
       74,   74,  146,  119,  144,  124,  124,   97,  151,   98,
      119,   75,  147,  148,  152,   84,  254,   84,   99,   55,
      124,  124,   75,   56,   73,  253,   76,   77,   73,  153,
       76,   77,  158,  252,  159,  121,  121,   75,  161,   56,

      161,   75,  251,  162,  162,  122,  121,  121,   75,  250,
       56,   56,   75,  164,  164,   56,  122,  173,  174,  162,
      162,  249,   56,  122,  248,   56,  247,   56,  165,   56,
       55,  162,  162,  246,   56,  121,  121,  121,  121,  245,
      244,  243,  242,  241,  240,  122,  239,  122,  238,  237,
       56,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      227,   56,   56,  226,  225,  224,   56,  223,  222,  221,
      220,  219,  218,   56,  217,  216,   56,  215,   56,  214,
       56,   55,  213,  212,  211,   56,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,

      196,   56,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,   56,   56,  185,  184,  183,   56,  182,  181,
      180,  179,  178,  177,   56,  176,  175,   56,  172,   56,
      171,   56,   61,  170,  169,  168,  117,  167,  166,  160,
      155,  154,  149,  145,  142,  141,  140,  139,  138,  137,
      136,  135,   61,  134,  133,  132,  131,  130,  129,  128,
      127,  126,  125,   61,   61,  118,  114,  113,   61,  112,
      111,  106,  105,  102,   91,   61,   90,   86,   61,   80,
       61,   62,   61,   61,   57,   53,  260,  117,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,

      260,  260,  260,   61,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,   61,   61,  260,  260,  260,   61,
      260,  260,  260,  260,  260,  260,   61,  260,  260,   61,
      260,   61,  260,   61,   61,  260,  260,  260,  117,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,   61,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,   61,   61,  260,  260,  260,
       61,  260,  260,  260,  260,  260,  260,   61,  260,  260,
       61,  260,   61,  260,   61,   54,  260,   54,   60,  260,
       60,  120,  120,  120,  123,  260,  123,  163,  163,  163,

        3,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260
    } ;

static yyconst short int yy_chk[566] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    7,   10,   15,   50,    7,   17,
       11,   18,   39,   18,   18,   39,   15,   17,   17,  263,
       10,   19,   24,   24,    7,   20,   19,   20,   20,  112,
       11,   21,   19,   21,   21,    7,    7,  112,   20,   37,

        7,   11,   11,  258,   21,   50,   11,    7,   37,   20,
        7,  252,    7,   11,    7,   21,   11,   41,   11,   36,
       11,   26,   26,   29,   41,   29,   36,  250,   29,   29,
       33,   33,   36,   33,   38,  249,   38,   44,   44,   38,
       38,   69,   69,   70,   70,   84,   84,   44,   73,   73,
       44,  108,   69,   70,   85,   85,  247,  104,   74,   73,
       74,   74,  106,   69,  104,  124,  124,   38,  108,   38,
       73,   74,  106,  106,  109,   75,  246,   75,   38,   54,
       75,   75,   74,   54,   76,  244,   76,   76,   77,  109,
       77,   77,  113,  243,  113,  120,  120,   76,  119,   54,

      119,   77,  242,  119,  119,  120,  121,  121,   76,  241,
       54,   54,   77,  122,  122,   54,  121,  134,  134,  161,
      161,  240,   54,  122,  239,   54,  232,   54,  122,   54,
       55,  162,  162,  231,   55,  163,  163,  164,  164,  227,
      226,  225,  224,  222,  221,  163,  219,  164,  218,  217,
       55,  216,  215,  214,  212,  211,  210,  209,  207,  206,
      205,   55,   55,  204,  201,  200,   55,  198,  197,  195,
      194,  193,  192,   55,  191,  190,   55,  189,   55,  188,
       55,   56,  187,  186,  185,   56,  184,  182,  180,  179,
      176,  175,  174,  173,  170,  168,  167,  166,  160,  159,

      158,   56,  157,  156,  155,  154,  153,  152,  151,  150,
      149,  148,   56,   56,  147,  146,  145,   56,  143,  142,
      140,  139,  138,  137,   56,  136,  135,   56,  133,   56,
      132,   56,   60,  131,  130,  129,   60,  128,  127,  114,
      111,  110,  107,  105,  102,  101,  100,   99,   98,   97,
       96,   95,   60,   94,   93,   92,   91,   90,   89,   88,
       87,   82,   78,   60,   60,   68,   48,   47,   60,   46,
       45,   43,   42,   40,   35,   60,   34,   32,   60,   25,
       60,   14,   60,   61,    9,    6,    3,   61,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   61,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   61,   61,    0,    0,    0,   61,
        0,    0,    0,    0,    0,    0,   61,    0,    0,   61,
        0,   61,    0,   61,  117,    0,    0,    0,  117,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  117,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  117,  117,    0,    0,    0,
      117,    0,    0,    0,    0,    0,    0,  117,    0,    0,
      117,    0,  117,    0,  117,  261,    0,  261,  262,    0,
      262,  264,  264,  264,  265,    0,  265,  266,  266,  266,

      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260,  260,  260,  260,  260,  260,
      260,  260,  260,  260,  260
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ass5_13CS30021.l"
#define INITIAL 0
#line 2 "ass5_13CS30021.l"
#include "y.tab.h"
#include "ass5_13CS30021_translator.h"
#include <cstdlib>
#include <cstring>
#include <string>
extern void yyerror(const char *);
static void comment(void);
#line 585 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 76 "ass5_13CS30021.l"

#line 749 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 261 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 501 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 77 "ass5_13CS30021.l"
{return AUTO_KEYWORD;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 78 "ass5_13CS30021.l"
{return RESTRICT_KEYWORD;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 79 "ass5_13CS30021.l"
{return ENUM_KEYWORD;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 80 "ass5_13CS30021.l"
{return IF_KEYWORD;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 81 "ass5_13CS30021.l"
{return ELSE_KEYWORD;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 82 "ass5_13CS30021.l"
{return GOTO_KEYWORD;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 83 "ass5_13CS30021.l"
{return SWITCH_KEYWORD;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 84 "ass5_13CS30021.l"
{return CASE_KEYWORD;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 85 "ass5_13CS30021.l"
{return CONTINUE_KEYWORD;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 86 "ass5_13CS30021.l"
{return BREAK_KEYWORD;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 87 "ass5_13CS30021.l"
{return DEFAULT_KEYWORD;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 88 "ass5_13CS30021.l"
{return RETURN_KEYWORD;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 89 "ass5_13CS30021.l"
{return DOUBLE_KEYWORD;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 90 "ass5_13CS30021.l"
{return FLOAT_KEYWORD;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 91 "ass5_13CS30021.l"
{return UNSIGNED_KEYWORD;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 92 "ass5_13CS30021.l"
{return SIGNED_KEYWORD;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 93 "ass5_13CS30021.l"
{return LONG_KEYWORD;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 94 "ass5_13CS30021.l"
{return INT_KEYWORD;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 95 "ass5_13CS30021.l"
{return SHORT_KEYWORD;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 96 "ass5_13CS30021.l"
{return CHAR_KEYWORD;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 97 "ass5_13CS30021.l"
{return VOID_KEYWORD;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 98 "ass5_13CS30021.l"
{return SIZEOF_KEYWORD;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 99 "ass5_13CS30021.l"
{return BOOL_KEYWORD;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 100 "ass5_13CS30021.l"
{return COMPLEX_KEYWORD;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 101 "ass5_13CS30021.l"
{return IMAGINARY_KEYWORD;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 102 "ass5_13CS30021.l"
{return FOR_KEYWORD;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 103 "ass5_13CS30021.l"
{return DO_KEYWORD;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 104 "ass5_13CS30021.l"
{return WHILE_KEYWORD;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 105 "ass5_13CS30021.l"
{return CONST_KEYWORD;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 106 "ass5_13CS30021.l"
{return STATIC_KEYWORD;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 107 "ass5_13CS30021.l"
{return REGISTER_KEYWORD;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 108 "ass5_13CS30021.l"
{return EXTERN_KEYWORD;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 109 "ass5_13CS30021.l"
{return VOLATILE_KEYWORD;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 110 "ass5_13CS30021.l"
{return INLINE_KEYWORD;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 111 "ass5_13CS30021.l"
{return STRUCT_KEYWORD;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 112 "ass5_13CS30021.l"
{return TYPEDEF_KEYWORD;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 113 "ass5_13CS30021.l"
{return UNION_KEYWORD;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 115 "ass5_13CS30021.l"
{yylval.idAttr.name = new string(yytext); return IDENTIFIER;}                             
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 117 "ass5_13CS30021.l"
{yylval.intval = atoi(yytext); return INTEGER_CONSTANT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 118 "ass5_13CS30021.l"
{yylval.floatval = atof(yytext); return FLOAT_CONSTANT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 119 "ass5_13CS30021.l"
{return ENUM_CONSTANT;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 120 "ass5_13CS30021.l"
{yylval.charval = yytext[1]; return CHAR_CONSTANT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 121 "ass5_13CS30021.l"
{yylval.stringval = strdup(yytext); return STRING_LITERAL;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 122 "ass5_13CS30021.l"
{return ELLIPSIS;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 123 "ass5_13CS30021.l"
{return LEFT_SHIFT_EQUAL;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 124 "ass5_13CS30021.l"
{return RIGHT_SHIFT_EQUAL;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 125 "ass5_13CS30021.l"
{return VAL_AT;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 126 "ass5_13CS30021.l"
{return PLUS_PLUS;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 127 "ass5_13CS30021.l"
{return MINUS_MINUS;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 128 "ass5_13CS30021.l"
{return LEFT_SHIFT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 129 "ass5_13CS30021.l"
{return RIGHT_SHIFT;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 130 "ass5_13CS30021.l"
{return LESS_EQUAL;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 131 "ass5_13CS30021.l"
{return GREATER_EQUAL;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 132 "ass5_13CS30021.l"
{return EQUAL_EQUAL;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 133 "ass5_13CS30021.l"
{return NOT_EQUAL;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 134 "ass5_13CS30021.l"
{return LOGICAL_AND;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 135 "ass5_13CS30021.l"
{return LOGICAL_OR;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 136 "ass5_13CS30021.l"
{return STAR_EQUAL;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 137 "ass5_13CS30021.l"
{return BY_EQUAL;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 138 "ass5_13CS30021.l"
{return PERCENT_EQUAL;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 139 "ass5_13CS30021.l"
{return PLUS_EQUAL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 140 "ass5_13CS30021.l"
{return MINUS_EQUAL;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 141 "ass5_13CS30021.l"
{return AND_EQUAL;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 142 "ass5_13CS30021.l"
{return BITWISENOT_EQUAL;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 143 "ass5_13CS30021.l"
{return OR_EQUAL;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 144 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 145 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 146 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 147 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 148 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 149 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 150 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 151 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 152 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 153 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 154 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 155 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 156 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 157 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 158 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 159 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 160 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 161 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 162 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 163 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 164 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 165 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 166 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 167 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 168 "ass5_13CS30021.l"
{return yytext[0];}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 169 "ass5_13CS30021.l"
;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 170 "ass5_13CS30021.l"
;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 171 "ass5_13CS30021.l"
{}        
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 172 "ass5_13CS30021.l"
ECHO;
	YY_BREAK
#line 1302 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 261 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 261 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 260);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 172 "ass5_13CS30021.l"

